### ISSUE TITLE
System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

### ISSUE THREAD

**Issue by bobstay** [teeknofil/Crisis-Wordlist-Generator#2]
Bonjour,
J'ai rencontré quelques problèmes, c'est peut être moi le problème.
Bon travail quand même merci. 

C:\Users\²\Desktop\crisis>crisis.exe -6 -f livebox-sagem > E:\dico.txt

Exception non gérée : System.ArgumentOutOfRangeException: La valeur doit être inférieure à la taille actuelle maximale de la fenêtre de la console de 0 dans cette dimension. Notez que cette valeur dépend de la résolution d'écran et de la police de la console.
Nom du paramètre : width
La valeur réelle était 100.
   à System.Console.SetWindowSize(Int32 width, Int32 height)
   à crisis.Program.Main(String[] args)

C:\Users\²\Desktop\crisis>crisis.exe -6 -f livebox-sagem -u -o > E:\dico.txt

Exception non gérée : System.IO.IOException: Descripteur non valide

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.__Error.WinIOError()
   à System.Console.SetWindowSize(Int32 width, Int32 height)
   à crisis.Program.Main(String[] args)

**Comment by teeknofil** [comment]
Bonjour, 

Le problème vient de nous deux, quand j'ai codé crisis dans ces premier version j'avais pour objectif de générer des chaine de caractères sans répétition pour éviter de faire des combinaison inutiles. Du coups il est impossible par exemple de générer une chaine de caractère de 26 caractère quand il a que 16 caractère hexadécimal. Pour permettre de faire des répétition quand il à pas assez de caractère j'ai ajouté l'option -r qui permet de répéter tous les caractère mais qui va générer plus de combinaison inutile.

Si vous utilisez la redirection du terminal il ne faut pas utilisé l'option -o car l'api de crisis le gère automatiquement. Windows aussi ne gère pas la redirection dans un fichier avec crisis ( le fameux ">").

 Utilisé la version de sourgeforge qui est un peu plus stable la version actuelle du 13/11/2016 sur git hub est bêta . Je suis en train de reprogrammer crisis depuis le début pour mieux respecté les standard de la PPO. 

La version final aura une longue période de débogage car se sera une des dernier version publier qui sera juste maintenu pour faire d'éventuel correctif. Je précise qui faut venir hurler gentiment au moindre bug pour qui soit corrigé dans la prochaine mise à jour. 

Pour finir pour résoudre votre problème,  utiliser plutôt ces commande qui sont identique à la commande livebox.

-> crisis -3 -l 27 -f hex-upper -u > dico_WPA_de_1000Gio.txt (uniquement sur linux)
-> crisis -3 -l 27 -f hex-upper -u -o (fonctionne sur Windows et linux)

Sans vouloir être relou je suis obliger de vous rappeler pour être conforme a la loi et au logiciel de pentesting que vous devez pas utilisé crisis pour faire des attaque informatique sur du matériel qui vous appartient pas.
Bon week end.

**Comment by bobstay** [comment]
Bonjour merci pour votre réponse désolé pour la mienne un peu tardive.
Je jouerais sur ma livebox ce weekend  .
Cordialement

**Comment by bobstay** [comment]
Salut après relecture c'est plutot
crisis -3 -l **26** -f hex-upper -u -o
